sudo: required

language: node_js

services:
  - docker

node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "iojs"

before_script:
  - npm install

script:
  - docker-compose build
  - docker-compose up -d
  - docker exec whattime_api_1 npm test
