api:
  build: .
  environment:
    - "NODE_ENV=development"
  ports:
    - "3000:3000"
    - "5858:5858"
  volumes:
    - ./src:/app/src
    - ./test:/app/test
  links:
    - db
db:
  image: mongo:3.3
